apiVersion: v1
kind: Secret
metadata:
  name: seas-secret
type: Opaque
data:
  adminPassword: V2VsY29tZUAxCg==
  sysPassphrase: V2VsY29tZUAxCg==
  keyStorePassphrase: V2VsY29tZUAxCg==
  trustStorePassphrase: V2VsY29tZUAxCg==
