apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - seas-pvc.yaml
  - seas-secret.yaml

helmCharts:
  - name: ibm-seas
    releaseName: ibm-seas
    namespace: ibm-seas
    path: ./ibm-seas
    valuesFile: ../values.yaml